Repository SystemConsultantGroup/Git-Study, pull requests merged in 2024-04, with the labels that each got.

#17 [BUG] #12 Article empty field
  databases/articles.json
  package-lock.json
  routes/article.ctl.js
  routes/article.js
Labels: bug, :computer: backend

#20 [TEST] TEST
  routes/article.js
Labels: bug

#10 [FEAT] #8 Modify service port
  bin/www
Labels: enhancement, :computer: backend

#18 [FIX] #11 Naming Rule
  public/javascripts/post.js
Labels: enhancement, :art: frontend

#21 [FIX] #7 Post not working
  routes/article.js
Labels: bug, :computer: backend
